apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: infinite-loop-operator-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: infiniteloops.mlops.cnvrg.io
spec:
  group: mlops.cnvrg.io
  names:
    kind: InfiniteLoop
    listKind: InfiniteLoopList
    plural: infiniteloops
    singular: infiniteloop
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: InfiniteLoop is the Schema for the infiniteloops API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of InfiniteLoop
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of InfiniteLoop
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infinite-loop-operator-leader-election-role
  namespace: infinite-loop-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infinite-loop-operator-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infinite-loop-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infinite-loop-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infinite-loop-operator-leader-election-rolebinding
  namespace: infinite-loop-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infinite-loop-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: infinite-loop-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infinite-loop-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infinite-loop-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: infinite-loop-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infinite-loop-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infinite-loop-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: infinite-loop-operator-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: infinite-loop-operator-controller-manager-metrics-service
  namespace: infinite-loop-operator-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: infinite-loop-operator-controller-manager
  namespace: infinite-loop-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --leader-election-id=infinite-loop-operator
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        image: dimssss/infinite-loop:v0.10
        name: manager
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 10
