apiVersion: v1
kind: Pod
metadata:
  name: "test-pod-1"
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: "test-pod-1"
spec:
{% if add_toleration == "true" %}
  tolerations:
  - key: "foo"
    operator: "Equal"
    value: "bar"
    effect: "NoSchedule"
{% endif %}
  containers:
    - name: "test-pod-1"
      image: "ubuntu:18.04"
      command: [ "/bin/bash","-c","sleep infinity"]