# permissions for end users to edit infiniteloops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infiniteloop-editor-role
rules:
- apiGroups:
  - mlops.cnvrg.io
  resources:
  - infiniteloops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.cnvrg.io
  resources:
  - infiniteloops/status
  verbs:
  - get
